apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: fsm-akka
spec:
  cassandra:
    serverVersion: "4.0.1"
    datacenters:
      - metadata:
          name: dc1
        size: 3
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvmOptions:
            heap_initial_size: 512M
        stargate:
          size: 0
          heapSize: 256M