# CASSANDRA #
cassandra:
  enabled: true
  datacenter:
    name: "dc1"
    size: 1
# ELASTICSEARCH #
elasticsearch:
  enabled: true
  name: "elasticsearch"
  #M1
  #version: "7.16.3-arm64"
  version: "7.16.3"
  master:
    replicaCount: 3
    storageSize: 2Gi
    storageClass:
      enabled: false
      #name: disk
    resources:
      requests:
        memory: 2Gi
        cpu: 2
      limits:
        memory: 2Gi
        cpu: 2
    noAffinity: false
  ingest_data:
    replicaCount: 2
    storageSize: 2Gi
    storageClass:
      enabled: true
      #name: disk
    resources:
      request:
        memory: 2Gi
        cpu: 2
      limits:
        memory: 2Gi
        cpu: 2
    noAffinity: false
# KAFKA #
kafka:
  enabled: true
  clusterName: fsmakka-cluster
  replicas: 1
  version: 3.3.2
  resources:
    request:
      memory: 2Gi
      cpu: 1
    limit:
      memory: 4Gi
      cpu: 2
  jvmOptions:
    xms: 2G
    xmx: 4G
  topics:
    replicationFactor: 1
    partitions: 1
    retention:
      ms: 7200000
    segment:
      bytes: 1073741824
zookeeper:
  replicas: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 500m
    limits:
      memory: 512Mi
      cpu: 1
  jvmOptions:
    xms: 512m
    xmx: 512m