# ELASTICSEARCH #
elasticsearch:
  name: "elasticsearch"
  #version: "7.16.3-arm64"
  master:
    replicaCount: 1
    storageSize: 2Gi
    storageClass:
      enabled: false
      #name: disk
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 2
    noAffinity: true
  ingest_data:
    replicaCount: 3
    storageSize: 2Gi
    storageClass:
      enabled: true
      #name: disk
    resources:
      request:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 2
    noAffinity: true
# KAFKA #
kafka:
  replicas: 3
  resources:
    request:
      memory: 4Gi
      cpu: 500m
    limit:
      memory: 4Gi
      cpu: 2
  jvmOptions:
    xms: 4G
    xmx: 8G