name: Clean Infrastructure for a Future Branch
run-name: Cleaning up Infrastructure for Branch ${{ inputs.branch-name }} triggered via ${{ github.event_name }} by ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      branch-name:
        required: true
        type: string
      cluster-name-not-normalised:
        type: string
        required: true
jobs:
  calculate-namespace:
    runs-on: ubuntu-latest
    outputs:
      namespace: ${{ steps.findandreplace2.outputs.value }}
    steps:
      - id: findandreplace
        uses: mad9000/actions-find-and-replace-string@3
        with:
          source: ${{ inputs.branch-name }}
          find: '/'
          replace: '-'
          replaceAll: 'true'
      - id: findandreplace1
        uses: mad9000/actions-find-and-replace-string@3
        with:
          source: ${{ steps.findandreplace.outputs.value }}
          find: '.'
          replace: '-'
          replaceAll: 'true'
      - id: findandreplace2
        uses: mad9000/actions-find-and-replace-string@3
        with:
          source: ${{ steps.findandreplace1.outputs.value }}
          find: '_'
          replace: '-'
          replaceAll: 'true'
  clean-environment-for-branch:
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: mehmetsalgar/fsm-akka-github-workflows/.github/workflows/helm-install.yaml@master
    needs: calculate-namespace
    with:
      helm-command: "helm delete fsm-akka-infrastructure -n ${{ needs.calculate-namespace.outputs.namespace }}"
      cluster-name-not-normalised: "${{ inputs.cluster-name-not-normalised }}"
    secrets: inherit
