name: Clean Infrastructure for a Future Branch
run-name: Cleaning up Infrastructure for Branch ${{ inputs.branch-name }} triggered via ${{ github.event_name }} by ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      branch-name:
        required: true
        type: string
jobs:
  clean-environment-for-branch:
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: mehmetsalgar/fsm-akka-github-workflows/.github/workflows/helm-install.yaml@master
    with:
      helm-command: "helm delete fsm-akka-infrastructure -n ${{ needs.calculate-branch-name.outputs.branchName }}"
    secrets: inherit
