name: Clean Infrastructure for a Future Branch
run-name: Cleaning up Infrastructure for Branch ${{ inputs.branch-name }} triggered via ${{ github.event_name }} by ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      branch-name:
        required: true
        type: string
jobs:
  clean-environment-for-future-branch:
    runs-on: ubuntu-latest
    steps:
      - id: install-kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'
      #  - id: kubectl-set-context
      #    uses: azure/k8s-set-context@v1
      #    with:
      #      method: kubeconfig
      #      kubeconfig: ''
      #      context: 'k3d-poc-akka'
      #      - name: Run Kubectl Command
      #        run: |
      #          kubectl version
      - id: install
        uses: azure/setup-helm@v3
        with:
          version: '3.10.3'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: findandreplace
        uses: mad9000/actions-find-and-replace-string@2
        with:
          source: ${{ inputs.branch-name }}
          find: '/'
          replace: '-'
      - id: findandreplace1
        uses: mad9000/actions-find-and-replace-string@2
        with:
          source: ${{ steps.findandreplace.outputs.value }}
          find: '/'
          replace: '-'
      - name: Run Helm Command
        run: |
          cd helm
          helm version
          echo 'helm delete fsm-akka-infrastructure -n ${{ steps.findandreplace1.outputs.value }}'