name: Terraform Destroy
run-name: Terraform destroy triggered via ${{ github.event_name }} by ${{ github.actor }}
on:
#  schedule:
#    - cron: "0 19 * * *"
  workflow_dispatch:
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    env:
      TF_VAR_cluster_name: ${{ vars.GKE_CLUSTER_NAME }}
      TF_VAR_credential: ${{ secrets.GCP_CREDENTIALS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      - name: Terraform Workspace
        run: terraform workspace select fsmakka_nightly
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      - name: Show Destroy plan
        run: terraform plan -destroy
        continue-on-error: true
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      - name: Terraform Workspace Destroy
        run: |
          terraform workspace select default
          terraform workspace delete fsmakka_nightly
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
