name: Helm Publish Infrastructure with Gradle
run-name: Publishing Helm Chart for Infrastructure triggered via ${{ github.event_name }} by ${{ github.actor }}
on:
  push:
    paths-ignore:
      - '.github/**'
      - 'terraform/**'
jobs:
  call-helm-publish:
    uses: mehmetsalgar/fsm-akka-github-workflows/.github/workflows/helm-publish.yaml@master
    secrets: inherit