name: Helm Publish Infrastructure with Gradle
run-name: ${{ github.actor }}
on:
  push:
    paths-ignore:
      - '.github/**'
jobs:
  call-helm-publish:
    uses: mehmetsalgar/fsm-akka-github-workflows/.github/workflows/helm-publish.yaml@master
    secrets: inherit